[package]
name = "somewords"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.0"
chrono = "0.4.26"
clap = { version = "4.3.2", features = ["derive"] }
gix = "0.44.1"
loga = "0.1.3"
palette = "0.7.2"
pulldown-cmark = "0.9.3"
